In [ ]:
In this part everyone have to do their part.

# EXCERCISE 1

In [2]:
pip install pyreadstat

Requirement already satisfied: pyreadstat in /Users/camila/anaconda3/lib/python3.11/site-packages (1.2.6)
Requirement already satisfied: pandas>=1.2.0 in /Users/camila/anaconda3/lib/python3.11/site-packages (from pyreadstat) (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/camila/anaconda3/lib/python3.11/site-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/camila/anaconda3/lib/python3.11/site-packages (from pandas>=1.2.0->pyreadstat) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/camila/anaconda3/lib/python3.11/site-packages (from pandas>=1.2.0->pyreadstat) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /Users/camila/anaconda3/lib/python3.11/site-packages (from pandas>=1.2.0->pyreadstat) (1.24.3)
Requirement already satisfied: six>=1.5 in /Users/camila/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadstat) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install savReaderWriter

Collecting savReaderWriter
  Downloading savReaderWriter-3.4.2.tar.gz (50.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 MB 13.1 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: savReaderWriter
  Building wheel for savReaderWriter (setup.py) ... done
  Created wheel for savReaderWriter: filename=savReaderWriter-3.4.2-py3-none-any.whl size=51142024 sha256=3ca298417152b80b9c52f6a1fdca4dbfd47bd2e1a241b1a7f1d8453d456b8243
  Stored in directory: /Users/camila/Library/Caches/pip/wheels/54/fe/84/916d69bcc12089f634872e0863a9285b87496ae0c681af7e1f
Successfully built savReaderWriter
Installing collected packages: savReaderWriter
Successfully installed savReaderWriter-3.4.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import os
import pickle
import pandas as pd
import numpy as np
import urllib.request

In [2]:
import pyreadstat

In [3]:
rec_1 = pd.read_spss( r"../../_data/endes/2019/REC0111.sav" )
rec_2 = pd.read_spss( r"../../_data/endes/2019/RE223132.sav" )
rec_3 = pd.read_spss( r"../../_data/endes/2019/RE516171.sav" )

In [4]:
rec_1

,ID1,HHID,CASEID,V001,V002,V003,V004,V007,V008,V009,...,QD333_4,QD333_5,QD333_6,UBIGEO,V022,V005,V190,V191,mujeres12a49,NCONGLOME
0,2019.0,000100201,000100201 2,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,...,No,No,No,010101,3.0,154803.0,Rico,1.234450,Mujeres de 15 a 49 años de edad,7065.0
1,2019.0,000100201,000100201 3,1.0,2.0,3.0,1.0,2019.0,1434.0,1.0,...,No,No,No,010101,3.0,154803.0,Rico,1.234450,"Mujeres de 12 a 14 de edad, nunca embarazadas",7065.0
2,2019.0,000102801,000102801 2,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,...,No,No,No,010101,3.0,154803.0,Rico,1.295611,Mujeres de 15 a 49 años de edad,7065.0
3,2019.0,000102801,000102801 6,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,...,No,No,No,010101,3.0,154803.0,Rico,1.295611,Mujeres de 15 a 49 años de edad,7065.0
4,2019.0,000104801,000104801 2,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,...,No,No,No,010101,3.0,154803.0,Pobrer,-0.256431,Mujeres de 15 a 49 años de edad,7065.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38330,2019.0,325406201,325406201 2,3254.0,62.0,2.0,3254.0,2019.0,1440.0,12.0,...,No,No,No,250401,249.0,244995.0,El más pobre,-1.750187,Mujeres de 15 a 49 años de edad,15783.0
38331,2019.0,325406301,325406301 2,3254.0,63.0,2.0,3254.0,2019.0,1440.0,6.0,...,No,No,No,250401,249.0,244995.0,El más pobre,-1.676861,Mujeres de 15 a 49 años de edad,15783.0
38332,2019.0,325407001,325407001 2,3254.0,70.0,2.0,3254.0,2019.0,1440.0,7.0,...,No,No,No,250401,249.0,459792.0,El más pobre,-1.585333,Mujeres de 15 a 49 años de edad,15783.0
38333,2019.0,325407201,325407201 2,3254.0,72.0,2.0,3254.0,2019.0,1440.0,12.0,...,No,No,No,250401,249.0,459792.0,El más pobre,-1.650159,Mujeres de 15 a 49 años de edad,15783.0
38334,2019.0,325407401,325407401 2,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,...,No,No,No,250401,249.0,244995.0,El más pobre,-1.644720,Mujeres de 15 a 49 años de edad,15783.0

In [5]:
import pyreadstat

# Define the file paths
file_paths = [
    '../../_data/endes/2019/REC0111.sav',
    '../../_data/endes/2019/RE223132.sav',
    '../../_data/endes/2019/RE516171.sav'
]

# Define names for imported files and labels
file_names = ['rec_1', 'rec_2', 'rec_3']
var_labels = ['var_labels1', 'var_labels2', 'var_labels3']
value_labels = ['value_labels1', 'value_labels2', 'value_labels3']

# Initialize dictionaries to store dataframes and labels
dataframes = {}
variable_labels = {}
value_labels_dict = {}

# Loop through the files
for i, file_path in enumerate(file_paths):
    # Read the SPSS file
    df, meta = pyreadstat.read_sav(file_path)
    
    # Store the dataframe
    dataframes[file_names[i]] = df
    
    # Store variable labels
    variable_labels[var_labels[i]] = meta.column_labels
    
    # Store value labels
    value_labels_dict[value_labels[i]] = meta.variable_value_labels

# Access the imported data and labels
rec_1 = dataframes['rec_1']
var_labels1 = variable_labels['var_labels1']
value_labels1 = value_labels_dict['value_labels1']

rec_2 = dataframes['rec_2']
var_labels2 = variable_labels['var_labels2']
value_labels2 = value_labels_dict['value_labels2']

rec_3 = dataframes['rec_3']
var_labels3 = variable_labels['var_labels3']
value_labels3 = value_labels_dict['value_labels3']

In [6]:
# Print the first few rows of rec_1 and its variable labels
print("rec_1 DataFrame:")
rec_1.head()

rec_1 DataFrame:

,ID1,HHID,CASEID,V001,V002,V003,V004,V007,V008,V009,...,QD333_4,QD333_5,QD333_6,UBIGEO,V022,V005,V190,V191,mujeres12a49,NCONGLOME
0,2019.0,000100201,000100201 2,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,...,2.0,2.0,2.0,010101,3.0,154803.0,4.0,1.234450,2.0,7065.0
1,2019.0,000100201,000100201 3,1.0,2.0,3.0,1.0,2019.0,1434.0,1.0,...,2.0,2.0,2.0,010101,3.0,154803.0,4.0,1.234450,0.0,7065.0
2,2019.0,000102801,000102801 2,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,...,2.0,2.0,2.0,010101,3.0,154803.0,4.0,1.295611,2.0,7065.0
3,2019.0,000102801,000102801 6,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,...,2.0,2.0,2.0,010101,3.0,154803.0,4.0,1.295611,2.0,7065.0
4,2019.0,000104801,000104801 2,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,...,2.0,2.0,2.0,010101,3.0,154803.0,2.0,-0.256431,2.0,7065.0

In [7]:
print("\nVariable Labels for rec_1:")
var_labels1

Variable Labels for rec_1:

['Año',
 'Identificación Cuestionario del Hogar',
 'Identificación Cuestionario Individual',
 'Conglomerado',
 'Número de vivienda',
 'Número de línea de entrevistada',
 'Unidad de área final',
 'Año de la entrevista',
 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'Mes de nacimiento de la entrevistada',
 'Año de nacimiento de la entrevistada',
 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'Edad actual - entrevistada',
 'Edad actual por grupos de 5 años',
 'Integridad de la información para la fecha de nacimiento',
 'Resultado entrevista individual',
 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'Columna del mes de la entrevista',
 'Duración del calendario',
 'Número de columnas de calendario',
 'Muestra alguna vez casada',
 'Unidad de muestreo primario - conglomerado',
 'Dominio de ejemplo - Departamento',
 'Región',
 'Tipo de lugar de residencia',
 'El lugar de residencia en el que se entrevistó - De Facto',
 'Número de visitas',
 'Identificación del entrevistador',
 'Identificador del digitador',
 'Supervisor de campo',
 'Editor de campo',
 'Editor de la oficina',
 'Selección final del área de probabilidad',
 'Número de orden del esposo',
 'Altitud del conglomerado en metros',
 'Selección de hogar para hemoglobina',
 'Selección para módulo de estatus de mujeres',
 'Selección para módulo de violencia domestica',
 'Código y fase del país',
 'Dia de nacimeinto de la entrevistada',
 'Región',
 'Tipo de lugar de residencia',
 'Lugar de residencia de la infancia',
 'Cuanto tiempo tiene viviendo continuamente en el lugar de residencia actual',
 'Tipo de lugar de residencia anteriormente',
 'Nivel educativo más alto',
 'Año/grado de educación más alto aprobado',
 'Fuente principal de abasteciemiento de agua potable que utilizan en su hogar para tomar o beber',
 'Tiempo para llegar a la fuente de agua',
 'Tipo de instalación sanitaria',
 'En su hogar tiene: electricidad',
 'En su hogar tiene: radio',
 'En su hogar tiene: televisión',
 'En su hogar tiene: refrigerador',
 'En su hogar tiene: bicicleta',
 'En su hogar tiene: motocicleta/motocar',
 'En su hogar tiene: coche/camión',
 'Material predominante del piso de la vivienda',
 'Material predominante de las paredes exteriores de la vivienda',
 'Material predominante del techo de la vivienda',
 'Religión',
 'Etnicidad',
 'Educación en años simples',
 'El lugar en el que se realizó la entrevista  De-facto',
 'Residente habitual o visitante',
 'Número de miembros del hogar',
 'Número de niños de 6 años de edad',
 'Número de mujeres de 15 a 49 años de edad elegibles en el hogar',
 'Región, residencia habitual De-jure',
 'Tipo de área de residencia De-jure',
 'Lugar de residencia De-jure',
 'Logro educativo',
 'Relación con el jefe del hogar',
 'Sexo del Jefe del Hogar',
 'Edad del jefe del hogar',
 'En su hogar tiene: teléfono',
 'Factor todas las mujeres - total',
 'Factor todas las mujeres - urbano/rural',
 'Factor todas las mujeres - regional',
 'Factor todas las mujeres - educación',
 'Factor todas las mujeres - índice de riqueza',
 'Alfabetización',
 'Alguna vez participó en un programa de alfabetización (no incluyendo la escuela primaria)',
 'Frecuencia de lectura de un periódico o revista',
 'Frecuencia de escuchar radio',
 'Frecuencia de ver televisión',
 'Baño compartido con otros hogares',
 'Tipo de combustible para cocinar',
 'Resultados de la prueba del yodo en la sal',
 'Número de viajes en los últimos 12 meses',
 'Afuera más de un mes en los últimos 12 meses',
 'Tipo de mosquitero que utilizo para dormir última noche',
 'Alguna dificultad o limitación permanente para ver, aún usando anteojos',
 'Alguna dificultad o limitación permanente para oir, aún usando audífonos',
 'Alguna dificultad o limitación permanente para hablar o comunicarse, aún usando la lengua de señas u otro',
 'Alguna dificultad o limitación permanente para moverse o caminar para usar brazos y/o piernas',
 'Alguna dificultad o limitación permanente para entender o aprender (concentrarse y recordarse)',
 'Alguna dificultad o limitación permanente para relacionarse con los demás, por sus pensamientos, sentimientos, emociones o conductas',
 'Código de Ubicación Gegráfica',
 'Estratos',
 'Factor de ponderacion',
 'Índice de riqueza',
 'Factor de puntuación del índice de riqueza (5 decimales)',
 'Mujeres de 12 a 49 años de edad',
 'Número de Conglomerado (proveniente del marco)']

In [8]:
print("\nValue Labels for rec_1:")
value_labels1

Value Labels for rec_1:

{'V013': {0.0: 'De 12 a 14 años de edad',
  1.0: 'De 15 a 19 años de edad',
  2.0: 'De 20 a 24 años de edad',
  3.0: 'De 25 a 29 años de edad',
  4.0: 'De 30 a 34 años de edad',
  5.0: 'De 35 a 39 años de edad',
  6.0: 'De 40 a 44 años de edad',
  7.0: 'De 45 a 49 años de edad'},
 'V014': {1.0: 'Mes y año',
  2.0: 'Mes y edad - año imputado',
  3.0: 'Año y edad - mes imputado',
  4.0: 'Año y edad - año ignorado supera el año de entrevista',
  5.0: 'Año - edad y mes imputados',
  6.0: 'Edad - año y mes imputados',
  7.0: 'Mes - edad y año imputados',
  8.0: 'Ninguno - edad, mes y año imputados'},
 'V015': {1.0: 'Completa',
  2.0: 'Ausente',
  3.0: 'Aplazada',
  4.0: 'Rechazada',
  5.0: 'Incoompleta',
  6.0: 'Discapacitada',
  7.0: 'Otra'},
 'V018': {0.0: 'Sin calendario'},
 'V019': {0.0: 'Sin calendario'},
 'V020': {0.0: 'Toda la mujer muestra', 1.0: 'Alguna muestra casada'},
 'V023': {1.0: 'Amazonas',
  2.0: 'Ancash',
  3.0: 'Apurimac',
  4.0: 'Arequipa',
  5.0: 'Ayacucho',
  6.0: 'Cajamarca',
  7.0: 'Callao',
  8.0: 'Cusco',
  9.0: 'Huancavelica',
  10.0: ' Huanuco',
  11.0: ' Ica',
  12.0: ' Junin',
  13.0: ' La Libertad',
  14.0: ' Lambayeque',
  15.0: ' Lima',
  16.0: ' Loreto',
  17.0: ' Madre de Dios',
  18.0: ' Moquegua',
  19.0: ' Pasco',
  20.0: ' Piura',
  21.0: ' Puno',
  22.0: ' San Martin',
  23.0: ' Tacna',
  24.0: ' Tumbes',
  25.0: ' Ucayali'},
 'V024': {1.0: 'Amazonas',
  2.0: 'Ancash',
  3.0: 'Apurimac',
  4.0: 'Arequipa',
  5.0: 'Ayacucho',
  6.0: 'Cajamarca',
  7.0: 'Callao',
  8.0: 'Cusco',
  9.0: 'Huancavelica',
  10.0: ' Huanuco',
  11.0: ' Ica',
  12.0: ' Junin',
  13.0: ' La Libertad',
  14.0: ' Lambayeque',
  15.0: ' Lima',
  16.0: ' Loreto',
  17.0: ' Madre de Dios',
  18.0: ' Moquegua',
  19.0: ' Pasco',
  20.0: ' Piura',
  21.0: ' Puno',
  22.0: ' San Martin',
  23.0: ' Tacna',
  24.0: ' Tumbes',
  25.0: ' Ucayali'},
 'V025': {1.0: 'Urbano', 2.0: 'Rural'},
 'V026': {0.0: 'Capital, gran ciudad',
  1.0: 'Pequeña ciudad',
  2.0: 'Pueblo',
  3.0: 'Campo'},
 'V034': {0.0: 'El esposo no está en el hogar'},
 'V042': {0.0: 'No sabeleccionado', 1.0: 'Seleccionado'},
 'V043': {0.0: 'Mujer No sabeleccionada', 1.0: 'Mujer seleccionada'},
 'V044': {0.0: 'Mujer No sabeleccionada',
  1.0: 'Mujer seleccionada y entrevistada',
  2.0: 'Mujer seleccionada, pero la privacidad no es posible',
  3.0: 'Mujer seleccionada, pero no entrevistada'},
 'Q105DD': {31.0: '1', 98.0: 'No sabe el dia'},
 'V101': {1.0: 'Amazonas',
  2.0: 'Ancash',
  3.0: 'Apurimac',
  4.0: 'Arequipa',
  5.0: 'Ayacucho',
  6.0: 'Cajamarca',
  7.0: 'Callao',
  8.0: 'Cusco',
  9.0: 'Huancavelica',
  10.0: 'Huanuco',
  11.0: 'Ica',
  12.0: 'Junin',
  13.0: 'La Libertad',
  14.0: 'Lambayeque',
  15.0: 'Lima',
  16.0: 'Loreto',
  17.0: 'Madre de Dios',
  18.0: 'Moquegua',
  19.0: 'Pasco',
  20.0: 'Piura',
  21.0: 'Puno',
  22.0: 'San Martin',
  23.0: 'Tacna',
  24.0: 'Tumbes',
  25.0: 'Ucayali'},
 'V102': {1.0: 'Urbano', 2.0: 'Rural'},
 'V103': {0.0: 'Capital, gran ciudad',
  1.0: 'Ciudad',
  2.0: 'Pueblo',
  3.0: 'Campo',
  4.0: 'En el extranjero'},
 'V104': {95.0: 'Siempre',
  96.0: 'Visitante',
  97.0: 'Inconsistente',
  98.0: 'No sabe'},
 'V105': {0.0: 'Capital, gran ciudad',
  1.0: 'Ciudad',
  2.0: 'Pueblo',
  3.0: 'Campo',
  4.0: 'En el extranjero'},
 'V106': {0.0: 'Sin educación',
  1.0: 'Primario',
  2.0: 'Secundario',
  3.0: 'Mayor'},
 'V113': {11.0: 'Dentro de la vivienda',
  12.0: 'Fuera de la vivienda, pero dentro del edificio',
  13.0: 'Pilón/Grifo público',
  21.0: 'Pozo en la casa/patio/lote',
  22.0: 'Pozo Público',
  41.0: 'Manantial (puquio)',
  43.0: 'Río/Acequia/Laguna',
  51.0: 'Agua de lluvia',
  61.0: 'Camión tanque/Aguatero',
  71.0: 'Agua embotellada',
  96.0: 'Otro',
  97.0: 'No es residente habitual'},
 'V115': {996.0: 'En los lugares', 997.0: 'No residente de jure'},
 'V116': {11.0: 'Vivienda interior',
  12.0: 'Vivienda exterior',
  21.0: 'Letrina ventilada',
  22.0: 'Pozo séptico',
  23.0: 'Latrina (ciego o negro)',
  24.0: 'Latrina sobre el río/lago',
  31.0: 'Río, canal',
  32.0: 'Sin servicio',
  96.0: 'Otro',
  97.0: 'No es residente habitual'},
 'V119': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V120': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V121': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V122': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V123': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V124': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V125': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V127': {11.0: 'Tierra/arena',
  21.0: 'Madera (entablados)',
  31.0: 'Parquet o madera pulida',
  32.0: 'Làminas asfálticas, vinílicos o similares',
  33.0: 'Losetas, terrazos o similares',
  34.0: 'Cemento/ladrillo',
  96.0: 'Pona',
  97.0: 'Otro(pona)'},
 'V128': {11.0: 'Tablones/madera',
  12.0: 'Estera',
  13.0: 'Caña/bambu/pona/palma/troncos/tabique',
  21.0: 'Adobe o tapia tarrajeados',
  22.0: 'Quincha (caña con barro)',
  23.0: 'Piedra con barro',
  24.0: 'Cartón',
  31.0: 'Ladrillo o /Bloques de cemento',
  32.0: 'Piedra o sillar con cal o cemento',
  33.0: 'Tripley',
  41.0: 'Sin paredes',
  96.0: 'Otro',
  97.0: 'No es residente habitual'},
 'V129': {11.0: 'Paja, hojas de palmera etc.',
  12.0: 'Estera',
  21.0: 'Caña o estera con torta de barro',
  22.0: 'Cartón',
  31.0: 'Concreto armado',
  32.0: 'Madera',
  33.0: 'Tejas',
  34.0: 'Plancha de calamina, fibra de cemento o similares',
  41.0: 'Sin techo',
  96.0: 'Otro',
  97.0: 'No es residente habitual'},
 'V130': {96.0: 'Otra'},
 'V131': {1.0: 'Quechua',
  2.0: 'Aimara',
  3.0: 'Ashaninka',
  4.0: 'Awajún/Aguaruna',
  5.0: 'Shipibo/Konibo',
  6.0: 'Shawi/Chayahuita',
  7.0: 'Matsigenka/ Machiguenga',
  8.0: 'Achuar',
  9.0: 'Otra lengua nativa u originaria',
  10.0: 'Castellano',
  11.0: 'Portugués',
  12.0: 'Otra lengua extranjera'},
 'V133': {97.0: 'Inconsistente'},
 'V134': {0.0: 'Capital, ciudad grande',
  1.0: 'Ciudad pequeña',
  2.0: 'Pueblo',
  3.0: 'Campo'},
 'V135': {1.0: 'Residente habitual', 2.0: 'Visitante'},
 'V139': {0.0: 'En el extranjero',
  1.0: 'Amazonas',
  2.0: 'Ancash',
  3.0: 'Apurimac',
  4.0: 'Arequipa',
  5.0: 'Ayacucho',
  6.0: 'Cajamarca',
  7.0: 'Callao',
  8.0: 'Cusco',
  9.0: 'Huancavelica',
  10.0: 'Huanuco',
  11.0: 'Ica',
  12.0: 'Junin',
  13.0: 'La Libertad',
  14.0: 'Lambayeque',
  15.0: 'Lima',
  16.0: 'Loreto',
  17.0: 'Madre de Dios',
  18.0: 'Moquegua',
  19.0: 'Pasco',
  20.0: 'Piura',
  21.0: 'Puno',
  22.0: 'San Martin',
  23.0: 'Tacna',
  24.0: 'Tumbes',
  25.0: 'Ucayali',
  97.0: 'No es residente habitual'},
 'V140': {1.0: 'Área urbana',
  2.0: 'Área rural',
  7.0: 'No es residente habitual'},
 'V141': {0.0: 'Capital, ciudad grande',
  1.0: 'Ciudad pequeña',
  2.0: 'Pueblo',
  3.0: 'Campo',
  7.0: 'No es residente habitual'},
 'V149': {0.0: 'Sin educación',
  1.0: 'Primaria incompleta',
  2.0: 'Primaria completa',
  3.0: 'Secundaria incompleta',
  4.0: 'Secundaria completa',
  5.0: 'Superior'},
 'V150': {1.0: 'Jefe del hogar',
  2.0: 'Esposa/esposo',
  3.0: 'Hijo/Hija',
  4.0: 'Yerno/Nuera',
  5.0: 'Nieto/Nieta',
  6.0: 'Padre/Madre',
  7.0: 'Suegro/Suegra',
  8.0: 'Hermano/a',
  9.0: 'Conviviente',
  10.0: 'Otro pariente',
  11.0: 'Hijo adoptado/hijo de crianza',
  12.0: 'Sin parentesco',
  15.0: 'Empleada domésdtica',
  98.0: 'No sabe'},
 'V151': {1.0: 'Hombre', 2.0: 'Mujer'},
 'V152': {97.0: '97+', 98.0: 'NS'},
 'V153': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V155': {0.0: 'No puede leer',
  1.0: 'Puede leer sólo parte de la frase',
  2.0: 'Puede leer la frase',
  3.0: 'No hay tarjeta en el idioma requerido',
  4.0: 'Ciega/problemas visuales'},
 'V156': {0.0: 'No', 1.0: 'Si'},
 'V157': {0.0: 'Nunca',
  1.0: 'De vez en cuando',
  2.0: 'Una vez por semana',
  3.0: 'Casi todos los días'},
 'V158': {0.0: 'Nunca',
  1.0: 'De vez en cuando',
  2.0: 'Una vez por semana',
  3.0: 'Casi todos los días'},
 'V159': {0.0: 'Nunca',
  1.0: 'De vez en cuando',
  2.0: 'Una vez por semana',
  3.0: 'Casi todos los días'},
 'V160': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V161': {1.0: 'Electricidad',
  2.0: 'Gas Licuado (GLP)',
  3.0: 'Gas natural(Tuberia)',
  5.0: 'Kerosene',
  6.0: 'Carbón mineral',
  7.0: 'Carbon vegetal',
  8.0: 'Leña',
  9.0: 'Cañas/Arbustos (secos)',
  10.0: 'Residuos agricolas',
  11.0: 'Bosta',
  95.0: 'No cocina',
  96.0: 'Otro',
  97.0: 'No es residente habitual'},
 'V166': {0.0: 'Sin coloración  - 0 ppm (sin yodo)',
  7.0: 'Coloración tenue - 7 ppm',
  15.0: 'Coloración azul o morado - 15 ppm',
  30.0: 'Coloración morado oscuro - 30 ppm a más',
  994.0: 'No se pudo realizar la prueba',
  995.0: 'No hay sal en el hogar'},
 'V167': {0.0: 'Ninguno'},
 'V168': {0.0: 'No', 1.0: 'Si'},
 'ML101': {0.0: 'Sin mosquitero',
  1.0: 'Solo mosquiteros tratados',
  2.0: 'Ambos mosquiteros tratados y no tratados',
  3.0: 'Solo mosquiteros no tratados'},
 'QD333_1': {1.0: 'Si', 2.0: 'No'},
 'QD333_2': {1.0: 'Si', 2.0: 'No'},
 'QD333_3': {1.0: 'Si', 2.0: 'No'},
 'QD333_4': {1.0: 'Si', 2.0: 'No'},
 'QD333_5': {1.0: 'Si', 2.0: 'No'},
 'QD333_6': {1.0: 'Si', 2.0: 'No'},
 'V190': {1.0: 'El más pobre',
  2.0: 'Pobrer',
  3.0: 'Medio',
  4.0: 'Rico',
  5.0: 'Más rico'},
 'mujeres12a49': {0.0: 'Mujeres de 12 a 14 de edad, nunca embarazadas',
  1.0: 'Mujeres de 12 a 49 de edad, alguna vez emabrazadas',
  2.0: 'Mujeres de 15 a 49 años de edad'}}

In [9]:
columns_rec1 = ['CASEID', 'V000', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008', 'V009', 'V010', 'V011', 'V012', 'V024', 'V102', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127', 'V133']
columns_rec2 = ['CASEID', 'V201', 'V218', 'V301', 'V302', 'V323', 'V323A', 'V325A', 'V326', 'V327', 'V337', 'V359', 'V360', 'V361', 'V362', 'V363', 'V364', 'V367', 'V372', 'V372A', 'V375A', 'V376', 'V376A', 'V379', 'V380']
columns_rec3 = ['CASEID', 'V501', 'V502', 'V503', 'V504', 'V505', 'V506', 'V507', 'V508', 'V509', 'V510', 'V511', 'V512', 'V513', 'V525', 'V613', 'V714', 'V715']

# Filtering selected columns for each dataset
rec1_1 = rec_1.loc[:, columns_rec1]
rec2_1 = rec_2.loc[:, columns_rec2]
rec3_1 = rec_3.loc[:, columns_rec3]

In [10]:
rec1_1

,CASEID,V000,V001,V002,V003,V004,V007,V008,V009,V010,...,V024,V102,V120,V121,V122,V123,V124,V125,V127,V133
0,000100201 2,PE6,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,1986.0,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,33.0,16.0
1,000100201 3,PE6,1.0,2.0,3.0,1.0,2019.0,1434.0,1.0,2007.0,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,33.0,6.0
2,000102801 2,PE6,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,1983.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,33.0,16.0
3,000102801 6,PE6,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,1970.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,33.0,4.0
4,000104801 2,PE6,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,1991.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38330,325406201 2,PE6,3254.0,62.0,2.0,3254.0,2019.0,1440.0,12.0,1971.0,...,25.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,4.0
38331,325406301 2,PE6,3254.0,63.0,2.0,3254.0,2019.0,1440.0,6.0,1988.0,...,25.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,6.0
38332,325407001 2,PE6,3254.0,70.0,2.0,3254.0,2019.0,1440.0,7.0,1973.0,...,25.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,3.0
38333,325407201 2,PE6,3254.0,72.0,2.0,3254.0,2019.0,1440.0,12.0,1994.0,...,25.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,9.0
38334,325407401 2,PE6,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,1996.0,...,25.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,9.0

# EXCERCISE 2

In [11]:
# Select columns for rec1
selected_columns_rec1 = [
    'CASEID', 'V000', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008', 'V009', 'V010',
    'V011', 'V012', 'V024', 'V102', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127', 'V133'
]

# Create a new dataframe for rec1 with selected columns
rec1_1 = rec_1.loc[:, selected_columns_rec1]

# Update the variable labels object for rec1
new_var_labels1 = variable_labels['var_labels1'][:len(selected_columns_rec1)]

# Update the value labels object for rec1
new_value_labels1 = {col: value_labels1.get(col, {}) for col in selected_columns_rec1}

# Update the dataframes and labels dictionaries
dataframes['rec1_1'] = rec1_1
variable_labels['new_var_labels1'] = new_var_labels1
value_labels_dict['new_value_labels1'] = new_value_labels1

In [12]:
rec1_1

,CASEID,V000,V001,V002,V003,V004,V007,V008,V009,V010,...,V024,V102,V120,V121,V122,V123,V124,V125,V127,V133
0,000100201 2,PE6,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,1986.0,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,33.0,16.0
1,000100201 3,PE6,1.0,2.0,3.0,1.0,2019.0,1434.0,1.0,2007.0,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,33.0,6.0
2,000102801 2,PE6,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,1983.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,33.0,16.0
3,000102801 6,PE6,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,1970.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,33.0,4.0
4,000104801 2,PE6,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,1991.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38330,325406201 2,PE6,3254.0,62.0,2.0,3254.0,2019.0,1440.0,12.0,1971.0,...,25.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,4.0
38331,325406301 2,PE6,3254.0,63.0,2.0,3254.0,2019.0,1440.0,6.0,1988.0,...,25.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,6.0
38332,325407001 2,PE6,3254.0,70.0,2.0,3254.0,2019.0,1440.0,7.0,1973.0,...,25.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,3.0
38333,325407201 2,PE6,3254.0,72.0,2.0,3254.0,2019.0,1440.0,12.0,1994.0,...,25.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,9.0
38334,325407401 2,PE6,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,1996.0,...,25.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,9.0

In [13]:
# Select columns for rec2
selected_columns_rec2 = [
    'CASEID', 'V201', 'V218', 'V301', 'V302', 'V323', 'V323A', 'V325A', 'V326', 'V327',
    'V337', 'V359', 'V360', 'V361', 'V362', 'V363', 'V364', 'V367', 'V372', 'V372A', 
    'V375A', 'V376', 'V376A', 'V379', 'V380'
]

# Create a new dataframe for rec1 with selected columns
rec2_1 = rec_2.loc[:, selected_columns_rec2]

# Update the variable labels object for rec1
new_var_labels2 = variable_labels['var_labels2'][:len(selected_columns_rec2)]

# Update the value labels object for rec1
new_value_labels2 = {col: value_labels2.get(col, {}) for col in selected_columns_rec2}

# Update the dataframes and labels dictionaries
dataframes['rec2_1'] = rec2_1
variable_labels['new_var_labels2'] = new_var_labels2
value_labels_dict['new_value_labels2'] = new_value_labels2

In [14]:
rec2_1

,CASEID,V201,V218,V301,V302,V323,V323A,V325A,V326,V327,...,V363,V364,V367,V372,V372A,V375A,V376,V376A,V379,V380
0,000100201 2,2.0,2.0,0.0,3.0,NaN,NaN,NaN,22.0,5.0,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,000100201 3,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,000102801 2,3.0,3.0,0.0,3.0,NaN,NaN,NaN,15.0,1.0,...,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,000102801 6,3.0,3.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,23.0,24.0,NaN,NaN,NaN
4,000104801 2,3.0,3.0,0.0,3.0,NaN,NaN,NaN,13.0,1.0,...,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36917,325406201 2,5.0,5.0,0.0,3.0,NaN,NaN,NaN,13.0,1.0,...,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36918,325406301 2,5.0,5.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36919,325407001 2,8.0,7.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36920,325407201 2,2.0,1.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36921,325407401 2,1.0,1.0,0.0,3.0,NaN,NaN,NaN,13.0,1.0,...,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# Select columns for rec3
selected_columns_rec3 = [
    'CASEID', 'V501', 'V502', 'V503', 'V504', 'V505', 'V506', 'V507', 'V508', 'V509',
    'V510', 'V511', 'V512', 'V513', 'V525', 'V613', 'V714', 'V715'
]

# Create a new dataframe for rec1 with selected columns
rec3_1 = rec_3.loc[:, selected_columns_rec3]

# Update the variable labels object for rec1
new_var_labels3 = variable_labels['var_labels3'][:len(selected_columns_rec3)]

# Update the value labels object for rec1
new_value_labels3 = {col: value_labels3.get(col, {}) for col in selected_columns_rec3}

# Update the dataframes and labels dictionaries
dataframes['rec3_1'] = rec3_1
variable_labels['new_var_labels3'] = new_var_labels3
value_labels_dict['new_value_labels3'] = new_value_labels3

In [16]:
rec3_1

,CASEID,V501,V502,V503,V504,V505,V506,V507,V508,V509,V510,V511,V512,V513,V525,V613,V714,V715
0,000100201 2,1.0,1.0,1.0,1.0,NaN,NaN,1.0,2008.0,1297.0,1.0,21.0,11.0,3.0,17.0,2.0,1.0,11.0
1,000102801 2,2.0,1.0,1.0,1.0,NaN,NaN,12.0,2011.0,1344.0,1.0,28.0,7.0,2.0,18.0,3.0,1.0,14.0
2,000102801 6,5.0,2.0,1.0,NaN,NaN,NaN,8.0,1984.0,1016.0,5.0,14.0,34.0,7.0,14.0,0.0,0.0,6.0
3,000104801 2,2.0,1.0,1.0,1.0,NaN,NaN,12.0,2009.0,1320.0,1.0,18.0,9.0,2.0,15.0,2.0,0.0,6.0
4,000113601 2,2.0,1.0,2.0,1.0,NaN,NaN,12.0,2005.0,1272.0,1.0,17.0,13.0,3.0,15.0,2.0,1.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33306,325406201 2,2.0,1.0,2.0,1.0,NaN,NaN,12.0,1985.0,1032.0,1.0,14.0,34.0,7.0,12.0,3.0,0.0,5.0
33307,325406301 2,2.0,1.0,1.0,1.0,NaN,NaN,12.0,2002.0,1236.0,1.0,14.0,17.0,4.0,12.0,3.0,0.0,7.0
33308,325407001 2,2.0,1.0,1.0,1.0,NaN,NaN,11.0,1986.0,1043.0,1.0,13.0,33.0,7.0,12.0,4.0,0.0,5.0
33309,325407201 2,2.0,1.0,1.0,1.0,NaN,NaN,5.0,2008.0,1301.0,1.0,13.0,11.0,3.0,13.0,2.0,0.0,11.0
33310,325407401 2,2.0,1.0,1.0,1.0,NaN,NaN,6.0,2013.0,1362.0,1.0,16.0,6.0,2.0,15.0,2.0,0.0,11.0

# EXCERCISE 3

In [17]:
# Adding a new column 'year' to rec1_1 using loc
rec1_1.loc[:, 'year'] = 2019

# Updating variable labels dictionary using update
new_var_labels1.append({'year': "Year of the survey"})

In [18]:
rec1_1

,CASEID,V000,V001,V002,V003,V004,V007,V008,V009,V010,...,V102,V120,V121,V122,V123,V124,V125,V127,V133,year
0,000100201 2,PE6,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,1986.0,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,33.0,16.0,2019
1,000100201 3,PE6,1.0,2.0,3.0,1.0,2019.0,1434.0,1.0,2007.0,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,33.0,6.0,2019
2,000102801 2,PE6,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,1983.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,33.0,16.0,2019
3,000102801 6,PE6,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,1970.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,33.0,4.0,2019
4,000104801 2,PE6,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,1991.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0,1.0,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38330,325406201 2,PE6,3254.0,62.0,2.0,3254.0,2019.0,1440.0,12.0,1971.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,4.0,2019
38331,325406301 2,PE6,3254.0,63.0,2.0,3254.0,2019.0,1440.0,6.0,1988.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,6.0,2019
38332,325407001 2,PE6,3254.0,70.0,2.0,3254.0,2019.0,1440.0,7.0,1973.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,3.0,2019
38333,325407201 2,PE6,3254.0,72.0,2.0,3254.0,2019.0,1440.0,12.0,1994.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,9.0,2019
38334,325407401 2,PE6,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,1996.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,9.0,2019

# EXCERCISE 4

In [19]:
endes_2019 = pd.merge(rec1_1, rec2_1, on='CASEID').merge(rec3_1, on='CASEID')

In [20]:
endes_2019

,CASEID,V000,V001,V002,V003,V004,V007,V008,V009,V010,...,V508,V509,V510,V511,V512,V513,V525,V613,V714,V715
0,000100201 2,PE6,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,1986.0,...,2008.0,1297.0,1.0,21.0,11.0,3.0,17.0,2.0,1.0,11.0
1,000102801 2,PE6,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,1983.0,...,2011.0,1344.0,1.0,28.0,7.0,2.0,18.0,3.0,1.0,14.0
2,000102801 6,PE6,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,1970.0,...,1984.0,1016.0,5.0,14.0,34.0,7.0,14.0,0.0,0.0,6.0
3,000104801 2,PE6,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,1991.0,...,2009.0,1320.0,1.0,18.0,9.0,2.0,15.0,2.0,0.0,6.0
4,000113601 2,PE6,1.0,136.0,2.0,1.0,2019.0,1434.0,11.0,1988.0,...,2005.0,1272.0,1.0,17.0,13.0,3.0,15.0,2.0,1.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33306,325406201 2,PE6,3254.0,62.0,2.0,3254.0,2019.0,1440.0,12.0,1971.0,...,1985.0,1032.0,1.0,14.0,34.0,7.0,12.0,3.0,0.0,5.0
33307,325406301 2,PE6,3254.0,63.0,2.0,3254.0,2019.0,1440.0,6.0,1988.0,...,2002.0,1236.0,1.0,14.0,17.0,4.0,12.0,3.0,0.0,7.0
33308,325407001 2,PE6,3254.0,70.0,2.0,3254.0,2019.0,1440.0,7.0,1973.0,...,1986.0,1043.0,1.0,13.0,33.0,7.0,12.0,4.0,0.0,5.0
33309,325407201 2,PE6,3254.0,72.0,2.0,3254.0,2019.0,1440.0,12.0,1994.0,...,2008.0,1301.0,1.0,13.0,11.0,3.0,13.0,2.0,0.0,11.0
33310,325407401 2,PE6,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,1996.0,...,2013.0,1362.0,1.0,16.0,6.0,2.0,15.0,2.0,0.0,11.0

# EXCERCISE 5

In [21]:
var_labels = [new_var_labels1]
var_labels.extend(new_var_labels2)
var_labels.extend(new_var_labels3)
var_labels

[['Año',
  'Identificación Cuestionario del Hogar',
  'Identificación Cuestionario Individual',
  'Conglomerado',
  'Número de vivienda',
  'Número de línea de entrevistada',
  'Unidad de área final',
  'Año de la entrevista',
  'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
  'Mes de nacimiento de la entrevistada',
  'Año de nacimiento de la entrevistada',
  'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
  'Edad actual - entrevistada',
  'Edad actual por grupos de 5 años',
  'Integridad de la información para la fecha de nacimiento',
  'Resultado entrevista individual',
  'Inicio del calendario, Codificación centenaria de mesesl CMC',
  'Columna del mes de la entrevista',
  'Duración del calendario',
  'Número de columnas de calendario',
  'Muestra alguna vez casada',
  'Unidad de muestreo primario - conglomerado',
  {'year': 'Year of the survey'}],
 'Año',
 'Identificación Cuestionario Individual',
 'Total de niños nacidos',
 '¿Cuántos hijos viven con usted?',
 '¿Cuántas hijas viven con usted?',
 '¿Cuántos hijos no están viviendo con usted?',
 '¿Cuántas hijas no están viviendo con usted?',
 '¿Cuántos hijos han muerto?',
 '¿Cuántas hijas han muerto?',
 'Nacimientos en los últimos cinco años',
 'Nacimientos del año pasado',
 'Nacimientos en el mes de entrevista',
 'Fecha del primer nacimiento, Codificación centenaria de meses (CMC)',
 'Edad del entrevistado al primer nacimiento',
 'Actualmente embarazada',
 'Duración del embarazo actual',
 'Tiempo transcurrido desde la última menstruación',
 'Menstruado en las últimas seis semanas',
 'Conocimiento del ciclo ovulatorio',
 'Número de niños vivos',
 'Número total de hijos vivos incluido el embarazo actual',
 'Número total de hijos vivos incluido el embarazo actual (6, si es mayor de 6)',
 'Intervalo entre la primera unión y primer nacimiento en meses',
 'Intervalo entre el último nacimiento y la fecha de la entrevista en meses',
 'Integridad de la información relativa a la fecha de la concepción del embarazo actual',
 'Año',
 'Identificación Cuestionario Individual',
 'Estado civil actual',
 'Actualmente, antes o nunca sacada',
 'Usted ha estado casada o conviviendo solo una vez, más de una vez',
 'Su esposo/compañer vive en el hogar o vive en otro lugar',
 'Número de otras esposas',
 'Número de rango de la esposa',
 'Mes - Primer matrimonio',
 'Año - Primer matrimonio',
 'Fecha del primer matrimonio (CMC)',
 'Integridad de la información para la fecha de inicio del primer matrimonio o unión',
 'Edad al primer matrimonio',
 'Años desde el primer matrimonio',
 'Duración del matrimonio (agrupado)',
 'Edad en la primera relación sexual',
 'Tiempo transcurrido desde la última relación sexual',
 'Tiempo transcurrido desde la última relación sexual en días']

In [22]:
value_labels = [new_value_labels1]
value_labels.extend(new_value_labels2)
value_labels.extend(new_value_labels3)
value_labels

[{'CASEID': {},
  'V000': {},
  'V001': {},
  'V002': {},
  'V003': {},
  'V004': {},
  'V007': {},
  'V008': {},
  'V009': {},
  'V010': {},
  'V011': {},
  'V012': {},
  'V024': {1.0: 'Amazonas',
   2.0: 'Ancash',
   3.0: 'Apurimac',
   4.0: 'Arequipa',
   5.0: 'Ayacucho',
   6.0: 'Cajamarca',
   7.0: 'Callao',
   8.0: 'Cusco',
   9.0: 'Huancavelica',
   10.0: ' Huanuco',
   11.0: ' Ica',
   12.0: ' Junin',
   13.0: ' La Libertad',
   14.0: ' Lambayeque',
   15.0: ' Lima',
   16.0: ' Loreto',
   17.0: ' Madre de Dios',
   18.0: ' Moquegua',
   19.0: ' Pasco',
   20.0: ' Piura',
   21.0: ' Puno',
   22.0: ' San Martin',
   23.0: ' Tacna',
   24.0: ' Tumbes',
   25.0: ' Ucayali'},
  'V102': {1.0: 'Urbano', 2.0: 'Rural'},
  'V120': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
  'V121': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
  'V122': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
  'V123': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
  'V124': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
  'V125': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
  'V127': {11.0: 'Tierra/arena',
   21.0: 'Madera (entablados)',
   31.0: 'Parquet o madera pulida',
   32.0: 'Làminas asfálticas, vinílicos o similares',
   33.0: 'Losetas, terrazos o similares',
   34.0: 'Cemento/ladrillo',
   96.0: 'Pona',
   97.0: 'Otro(pona)'},
  'V133': {97.0: 'Inconsistente'}},
 'CASEID',
 'V201',
 'V218',
 'V301',
 'V302',
 'V323',
 'V323A',
 'V325A',
 'V326',
 'V327',
 'V337',
 'V359',
 'V360',
 'V361',
 'V362',
 'V363',
 'V364',
 'V367',
 'V372',
 'V372A',
 'V375A',
 'V376',
 'V376A',
 'V379',
 'V380',
 'CASEID',
 'V501',
 'V502',
 'V503',
 'V504',
 'V505',
 'V506',
 'V507',
 'V508',
 'V509',
 'V510',
 'V511',
 'V512',
 'V513',
 'V525',
 'V613',
 'V714',
 'V715']

In [23]:
endes_2019.update({'var_labels': var_labels, 'value_labels': value_labels})