#ASSIGNMENT 3

In [1]:
pip install pyreadstat

Requirement already satisfied: pyreadstat in c:\users\guill\anaconda3\lib\site-packages (1.2.6)
Requirement already satisfied: pandas>=1.2.0 in c:\users\guill\anaconda3\lib\site-packages (from pyreadstat) (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\guill\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\guill\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\guill\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\guill\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\guill\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadstat) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install savReaderWriter

Requirement already satisfied: savReaderWriter in c:\users\guill\anaconda3\lib\site-packages (3.4.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pyreadstat

In [12]:
import os
import pickle
import pandas as pd
import numpy as np
import urllib.request

In [5]:
rec_1 = pyreadstat.read_sav( r"../../_data/endes/2019/REC0111.sav") 
rec_2 = pyreadstat.read_sav( r"../../_data/endes/2019/RE223132.sav")
rec_3 = pyreadstat.read_sav( r"../../_data/endes/2019/RE516171.sav")

rec_1

(          ID1             HHID              CASEID    V001  V002  V003  \
 0      2019.0        000100201        000100201  2     1.0   2.0   2.0
 1      2019.0        000100201        000100201  3     1.0   2.0   3.0
 2      2019.0        000102801        000102801  2     1.0  28.0   2.0
 3      2019.0        000102801        000102801  6     1.0  28.0   6.0
 4      2019.0        000104801        000104801  2     1.0  48.0   2.0
 ...       ...              ...                 ...     ...   ...   ...
 38330  2019.0        325406201        325406201  2  3254.0  62.0   2.0
 38331  2019.0        325406301        325406301  2  3254.0  63.0   2.0
 38332  2019.0        325407001        325407001  2  3254.0  70.0   2.0
 38333  2019.0        325407201        325407201  2  3254.0  72.0   2.0
 38334  2019.0        325407401        325407401  2  3254.0  74.0   2.0

          V004    V007    V008  V009  ...  QD333_4  QD333_5  QD333_6  UBIGEO  \
 0         1.0  2019.0  1434.0   4.0  ...      2.0      2.0      2.0  010101
 1         1.0  2019.0  1434.0   1.0  ...      2.0      2.0      2.0  010101
 2         1.0  2019.0  1434.0   6.0  ...      2.0      2.0      2.0  010101
 3         1.0  2019.0  1434.0   3.0  ...      2.0      2.0      2.0  010101
 4         1.0  2019.0  1434.0   5.0  ...      2.0      2.0      2.0  010101
 ...       ...     ...     ...   ...  ...      ...      ...      ...     ...
 38330  3254.0  2019.0  1440.0  12.0  ...      2.0      2.0      2.0  250401
 38331  3254.0  2019.0  1440.0   6.0  ...      2.0      2.0      2.0  250401
 38332  3254.0  2019.0  1440.0   7.0  ...      2.0      2.0      2.0  250401
 38333  3254.0  2019.0  1440.0  12.0  ...      2.0      2.0      2.0  250401
 38334  3254.0  2019.0  1440.0  10.0  ...      2.0      2.0      2.0  250401

         V022      V005  V190      V191  mujeres12a49  NCONGLOME
 0        3.0  154803.0   4.0  1.234450           2.0     7065.0
 1        3.0  154803.0   4.0  1.234450           0.0     7065.0
 2        3.0  154803.0   4.0  1.295611           2.0     7065.0
 3        3.0  154803.0   4.0  1.295611           2.0     7065.0
 4        3.0  154803.0   2.0 -0.256431           2.0     7065.0
 ...      ...       ...   ...       ...           ...        ...
 38330  249.0  244995.0   1.0 -1.750187           2.0    15783.0
 38331  249.0  244995.0   1.0 -1.676861           2.0    15783.0
 38332  249.0  459792.0   1.0 -1.585333           2.0    15783.0
 38333  249.0  459792.0   1.0 -1.650159           2.0    15783.0
 38334  249.0  244995.0   1.0 -1.644720           2.0    15783.0

 [38335 rows x 105 columns],
 <pyreadstat._readstat_parser.metadata_container at 0x1fb2e182d50>)

In [6]:
rec_2

(          ID1              CASEID  V201  V202  V203  V204  V205  V206  V207  \
 0      2019.0        000100201  2   2.0   1.0   1.0   0.0   0.0   0.0   0.0
 1      2019.0        000100201  3   0.0   0.0   0.0   0.0   0.0   0.0   0.0
 2      2019.0        000102801  2   3.0   1.0   2.0   0.0   0.0   0.0   0.0
 3      2019.0        000102801  6   3.0   1.0   0.0   2.0   0.0   0.0   0.0
 4      2019.0        000104801  2   3.0   1.0   2.0   0.0   0.0   0.0   0.0
 ...       ...                 ...   ...   ...   ...   ...   ...   ...   ...
 36917  2019.0        325406201  2   5.0   1.0   1.0   2.0   1.0   0.0   0.0
 36918  2019.0        325406301  2   5.0   2.0   2.0   0.0   1.0   0.0   0.0
 36919  2019.0        325407001  2   8.0   2.0   0.0   5.0   0.0   0.0   1.0
 36920  2019.0        325407201  2   2.0   1.0   0.0   0.0   0.0   1.0   0.0
 36921  2019.0        325407401  2   1.0   1.0   0.0   0.0   0.0   0.0   0.0

        V208  ...  V307_09  V307_10  V307_11  V307_12  V307_13  V307_14  \
 0       1.0  ...      NaN      NaN      NaN      NaN      NaN      NaN
 1       0.0  ...      NaN      NaN      NaN      NaN      NaN      NaN
 2       2.0  ...      0.0      0.0      NaN      NaN      NaN      NaN
 3       0.0  ...      NaN      NaN      NaN      NaN      NaN      NaN
 4       1.0  ...      NaN      NaN      NaN      NaN      NaN      NaN
 ...     ...  ...      ...      ...      ...      ...      ...      ...
 36917   1.0  ...      NaN      NaN      NaN      NaN      NaN      NaN
 36918   1.0  ...      0.0      1.0      NaN      NaN      NaN      NaN
 36919   0.0  ...      1.0      0.0      NaN      NaN      NaN      NaN
 36920   0.0  ...      NaN      NaN      NaN      NaN      NaN      NaN
 36921   1.0  ...      0.0      NaN      NaN      NaN      NaN      NaN

        V307_15  V307_16  QI302_05A  QI302_05B
 0          NaN      0.0        1.0        2.0
 1          NaN      NaN        NaN        NaN
 2          NaN      0.0        2.0        1.0
 3          NaN      NaN        2.0        2.0
 4          NaN      NaN        2.0        1.0
 ...        ...      ...        ...        ...
 36917      NaN      NaN        2.0        1.0
 36918      NaN      NaN        2.0        1.0
 36919      NaN      NaN        2.0        1.0
 36920      NaN      NaN        2.0        1.0
 36921      NaN      NaN        2.0        1.0

 [36922 rows x 176 columns],
 <pyreadstat._readstat_parser.metadata_container at 0x1fb3249c290>)

In [7]:
rec_3

(          ID1              CASEID  V501  V502  V503  V504  V505  V506  V507  \
 0      2019.0        000100201  2   1.0   1.0   1.0   1.0   NaN   NaN   1.0
 1      2019.0        000102801  2   2.0   1.0   1.0   1.0   NaN   NaN  12.0
 2      2019.0        000102801  6   5.0   2.0   1.0   NaN   NaN   NaN   8.0
 3      2019.0        000104801  2   2.0   1.0   1.0   1.0   NaN   NaN  12.0
 4      2019.0        000113601  2   2.0   1.0   2.0   1.0   NaN   NaN  12.0
 ...       ...                 ...   ...   ...   ...   ...   ...   ...   ...
 33306  2019.0        325406201  2   2.0   1.0   2.0   1.0   NaN   NaN  12.0
 33307  2019.0        325406301  2   2.0   1.0   1.0   1.0   NaN   NaN  12.0
 33308  2019.0        325407001  2   2.0   1.0   1.0   1.0   NaN   NaN  11.0
 33309  2019.0        325407201  2   2.0   1.0   1.0   1.0   NaN   NaN   5.0
 33310  2019.0        325407401  2   2.0   1.0   1.0   1.0   NaN   NaN   6.0

          V508  ...  V743C  V743D  V743E  V743F  V744A  V744B  V744C  V744D  \
 0      2008.0  ...    1.0    2.0    1.0    4.0    0.0    0.0    0.0    0.0
 1      2011.0  ...    2.0    1.0    1.0    2.0    0.0    0.0    0.0    0.0
 2      1984.0  ...    NaN    NaN    NaN    NaN    0.0    0.0    0.0    0.0
 3      2009.0  ...    1.0    1.0    1.0    1.0    0.0    0.0    0.0    0.0
 4      2005.0  ...    1.0    1.0    2.0    4.0    0.0    0.0    0.0    0.0
 ...       ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
 33306  1985.0  ...    2.0    2.0    2.0    2.0    0.0    0.0    0.0    0.0
 33307  2002.0  ...    1.0    1.0    1.0    2.0    0.0    0.0    0.0    0.0
 33308  1986.0  ...    4.0    4.0    1.0    2.0    0.0    0.0    0.0    0.0
 33309  2008.0  ...    4.0    1.0    1.0    2.0    0.0    0.0    0.0    0.0
 33310  2013.0  ...    4.0    4.0    1.0    2.0    0.0    0.0    0.0    0.0

        V744E  V746
 0        0.0   1.0
 1        0.0   2.0
 2        0.0   NaN
 3        0.0   NaN
 4        0.0   2.0
 ...      ...   ...
 33306    0.0   NaN
 33307    0.0   NaN
 33308    0.0   NaN
 33309    0.0   NaN
 33310    0.0   NaN

 [33311 rows x 84 columns],
 <pyreadstat._readstat_parser.metadata_container at 0x1fb3472e1d0>)

In [23]:
file_paths = [
    '../../_data/endes/2019/REC0111.sav',
    '../../_data/endes/2019/RE223132.sav',
    '../../_data/endes/2019/RE516171.sav']

file_names = ['rec_1', 'rec_2', 'rec_3']
var_labels = ['var_labels1', 'var_labels2', 'var_labels3']
value_labels = ['value_labels1', 'value_labels2', 'value_labels3']

# Initialize dictionaries to store dataframes and labels
dataframes = {}
variable_labels = {}
value_labels_dict = {}

# Loop through the files
for i, file_path in enumerate(file_paths):
    # Read the SPSS file
    df, meta = pyreadstat.read_sav(file_path)
    
    # Store the dataframe
    dataframes[file_names[i]] = df
    
    # Store variable labels
    variable_labels[var_labels[i]] = meta.column_labels
    
    # Store value labels
    value_labels_dict[value_labels[i]] = meta.variable_value_labels

# Access the imported data and labels
rec_1 = dataframes['rec_1']
var_labels1 = variable_labels['var_labels1']
value_labels1 = value_labels_dict['value_labels1']

rec_2 = dataframes['rec_2']
var_labels2 = variable_labels['var_labels2']
value_labels2 = value_labels_dict['value_labels2']

rec_3 = dataframes['rec_3']
var_labels3 = variable_labels['var_labels3']
value_labels3 = value_labels_dict['value_labels3']

In [24]:
sel_vars1 = "CASEID, V000, V001, V002, V003, V004, V007, V008, V009, V010, V011, V012, V024, V102, V120, V121, V122, V123, V124, V125, V127, V133"
sel_vars2 = "CASEID, V201, V218, V301, V302, V323, V323A, V325A, V326, V327, V337, V359, V360, V361, V362, V363, V364, V367, V372, V372A, V375A, V376, V376A, V379, V380" 
sel_vars3 = "CASEID, V501, V502, V503, V504, V505, V506, V507, V508, V509, V510, V511, V512, V513, V525, V613, V714, V715"

In [ ]:
rec1_1 = rec_1.loc[ :, sel_vars1 ]
rec2_1 = rec_2.loc[ :, sel_vars2 ]
rec3_1 = rec_3.loc[ :, sel_vars3 ]

In [26]:
print("rec_1 DataFrame:")
rec_1.head()

rec_1 DataFrame:

,ID1,HHID,CASEID,V001,V002,V003,V004,V007,V008,V009,...,QD333_4,QD333_5,QD333_6,UBIGEO,V022,V005,V190,V191,mujeres12a49,NCONGLOME
0,2019.0,000100201,000100201 2,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,...,2.0,2.0,2.0,010101,3.0,154803.0,4.0,1.234450,2.0,7065.0
1,2019.0,000100201,000100201 3,1.0,2.0,3.0,1.0,2019.0,1434.0,1.0,...,2.0,2.0,2.0,010101,3.0,154803.0,4.0,1.234450,0.0,7065.0
2,2019.0,000102801,000102801 2,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,...,2.0,2.0,2.0,010101,3.0,154803.0,4.0,1.295611,2.0,7065.0
3,2019.0,000102801,000102801 6,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,...,2.0,2.0,2.0,010101,3.0,154803.0,4.0,1.295611,2.0,7065.0
4,2019.0,000104801,000104801 2,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,...,2.0,2.0,2.0,010101,3.0,154803.0,2.0,-0.256431,2.0,7065.0